### ISSUE TITLE
[Feat] ChartView UI구현하기

### ISSUE THREAD

**Issue by JMM00** [mycookie1/CleannyRefactoring#7]
### 문제상황
- ChartView UI구현하기

### TODO
- [ ] 카테고리 버튼 넣기
- [ ] 카테고리 버튼 클릭 시 차트 reload
- [ ] 차트 커스텀 하기
